export { default as cloudfront } from './cloudfront'
export { default as dynamodb } from './dynamodb'
export { default as ec2 } from './ec2'
export { default as elasticache } from './elasticache'
export { default as elb } from './elb'
export { default as lambda } from './lambda'
export { default as rds } from './rds'
export { default as route53 } from './route53'
export { default as s3 } from './s3'
export { totalTable, totalTables } from './total'
