export { default as cloudfront } from '@/lib/calc/cloudfront'
export { default as dynamodb } from '@/lib/calc/dynamodb'
export { default as ec2 } from '@/lib/calc/ec2'
export { default as elasticache } from '@/lib/calc/elasticache'
export { default as elb } from '@/lib/calc/elb'
export { default as lambda } from '@/lib/calc/lambda'
export { default as rds } from '@/lib/calc/rds'
export { default as route53 } from '@/lib/calc/route53'
export { default as s3 } from '@/lib/calc/s3'
export { totalTable, totalTables } from '@/lib/calc/total'
